/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContactPropertyFailureResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactPropertyFailureResponse{}

// ContactPropertyFailureResponse struct for ContactPropertyFailureResponse
type ContactPropertyFailureResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
}

type _ContactPropertyFailureResponse ContactPropertyFailureResponse

// NewContactPropertyFailureResponse instantiates a new ContactPropertyFailureResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactPropertyFailureResponse(success bool, message string) *ContactPropertyFailureResponse {
	this := ContactPropertyFailureResponse{}
	this.Success = success
	this.Message = message
	return &this
}

// NewContactPropertyFailureResponseWithDefaults instantiates a new ContactPropertyFailureResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactPropertyFailureResponseWithDefaults() *ContactPropertyFailureResponse {
	this := ContactPropertyFailureResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ContactPropertyFailureResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ContactPropertyFailureResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ContactPropertyFailureResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *ContactPropertyFailureResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ContactPropertyFailureResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ContactPropertyFailureResponse) SetMessage(v string) {
	o.Message = v
}

func (o ContactPropertyFailureResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactPropertyFailureResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ContactPropertyFailureResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContactPropertyFailureResponse := _ContactPropertyFailureResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContactPropertyFailureResponse)

	if err != nil {
		return err
	}

	*o = ContactPropertyFailureResponse(varContactPropertyFailureResponse)

	return err
}

type NullableContactPropertyFailureResponse struct {
	value *ContactPropertyFailureResponse
	isSet bool
}

func (v NullableContactPropertyFailureResponse) Get() *ContactPropertyFailureResponse {
	return v.value
}

func (v *NullableContactPropertyFailureResponse) Set(val *ContactPropertyFailureResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContactPropertyFailureResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContactPropertyFailureResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactPropertyFailureResponse(val *ContactPropertyFailureResponse) *NullableContactPropertyFailureResponse {
	return &NullableContactPropertyFailureResponse{value: val, isSet: true}
}

func (v NullableContactPropertyFailureResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactPropertyFailureResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


