/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.3.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiKeyGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyGet200Response{}

// ApiKeyGet200Response struct for ApiKeyGet200Response
type ApiKeyGet200Response struct {
	Success bool `json:"success"`
	// The name of the team the API key belongs to.
	TeamName string `json:"teamName"`
}

type _ApiKeyGet200Response ApiKeyGet200Response

// NewApiKeyGet200Response instantiates a new ApiKeyGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyGet200Response(success bool, teamName string) *ApiKeyGet200Response {
	this := ApiKeyGet200Response{}
	this.Success = success
	this.TeamName = teamName
	return &this
}

// NewApiKeyGet200ResponseWithDefaults instantiates a new ApiKeyGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyGet200ResponseWithDefaults() *ApiKeyGet200Response {
	this := ApiKeyGet200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ApiKeyGet200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ApiKeyGet200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ApiKeyGet200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetTeamName returns the TeamName field value
func (o *ApiKeyGet200Response) GetTeamName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamName
}

// GetTeamNameOk returns a tuple with the TeamName field value
// and a boolean to check if the value has been set.
func (o *ApiKeyGet200Response) GetTeamNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamName, true
}

// SetTeamName sets field value
func (o *ApiKeyGet200Response) SetTeamName(v string) {
	o.TeamName = v
}

func (o ApiKeyGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["teamName"] = o.TeamName
	return toSerialize, nil
}

func (o *ApiKeyGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"teamName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiKeyGet200Response := _ApiKeyGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiKeyGet200Response)

	if err != nil {
		return err
	}

	*o = ApiKeyGet200Response(varApiKeyGet200Response)

	return err
}

type NullableApiKeyGet200Response struct {
	value *ApiKeyGet200Response
	isSet bool
}

func (v NullableApiKeyGet200Response) Get() *ApiKeyGet200Response {
	return v.value
}

func (v *NullableApiKeyGet200Response) Set(val *ApiKeyGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyGet200Response(val *ApiKeyGet200Response) *NullableApiKeyGet200Response {
	return &NullableApiKeyGet200Response{value: val, isSet: true}
}

func (v NullableApiKeyGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


