/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.4.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContactProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactProperty{}

// ContactProperty struct for ContactProperty
type ContactProperty struct {
	Key string `json:"key"`
	Label string `json:"label"`
	Type string `json:"type"`
}

type _ContactProperty ContactProperty

// NewContactProperty instantiates a new ContactProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactProperty(key string, label string, type_ string) *ContactProperty {
	this := ContactProperty{}
	this.Key = key
	this.Label = label
	this.Type = type_
	return &this
}

// NewContactPropertyWithDefaults instantiates a new ContactProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactPropertyWithDefaults() *ContactProperty {
	this := ContactProperty{}
	return &this
}

// GetKey returns the Key field value
func (o *ContactProperty) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ContactProperty) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ContactProperty) SetKey(v string) {
	o.Key = v
}

// GetLabel returns the Label field value
func (o *ContactProperty) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ContactProperty) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ContactProperty) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *ContactProperty) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContactProperty) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContactProperty) SetType(v string) {
	o.Type = v
}

func (o ContactProperty) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ContactProperty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"label",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContactProperty := _ContactProperty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContactProperty)

	if err != nil {
		return err
	}

	*o = ContactProperty(varContactProperty)

	return err
}

type NullableContactProperty struct {
	value *ContactProperty
	isSet bool
}

func (v NullableContactProperty) Get() *ContactProperty {
	return v.value
}

func (v *NullableContactProperty) Set(val *ContactProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableContactProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableContactProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactProperty(val *ContactProperty) *NullableContactProperty {
	return &NullableContactProperty{value: val, isSet: true}
}

func (v NullableContactProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


