/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.4.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IdempotencyKeyFailureResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdempotencyKeyFailureResponse{}

// IdempotencyKeyFailureResponse struct for IdempotencyKeyFailureResponse
type IdempotencyKeyFailureResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
}

type _IdempotencyKeyFailureResponse IdempotencyKeyFailureResponse

// NewIdempotencyKeyFailureResponse instantiates a new IdempotencyKeyFailureResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdempotencyKeyFailureResponse(success bool, message string) *IdempotencyKeyFailureResponse {
	this := IdempotencyKeyFailureResponse{}
	this.Success = success
	this.Message = message
	return &this
}

// NewIdempotencyKeyFailureResponseWithDefaults instantiates a new IdempotencyKeyFailureResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdempotencyKeyFailureResponseWithDefaults() *IdempotencyKeyFailureResponse {
	this := IdempotencyKeyFailureResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *IdempotencyKeyFailureResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *IdempotencyKeyFailureResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *IdempotencyKeyFailureResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *IdempotencyKeyFailureResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *IdempotencyKeyFailureResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *IdempotencyKeyFailureResponse) SetMessage(v string) {
	o.Message = v
}

func (o IdempotencyKeyFailureResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdempotencyKeyFailureResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *IdempotencyKeyFailureResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdempotencyKeyFailureResponse := _IdempotencyKeyFailureResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIdempotencyKeyFailureResponse)

	if err != nil {
		return err
	}

	*o = IdempotencyKeyFailureResponse(varIdempotencyKeyFailureResponse)

	return err
}

type NullableIdempotencyKeyFailureResponse struct {
	value *IdempotencyKeyFailureResponse
	isSet bool
}

func (v NullableIdempotencyKeyFailureResponse) Get() *IdempotencyKeyFailureResponse {
	return v.value
}

func (v *NullableIdempotencyKeyFailureResponse) Set(val *IdempotencyKeyFailureResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdempotencyKeyFailureResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdempotencyKeyFailureResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdempotencyKeyFailureResponse(val *IdempotencyKeyFailureResponse) *NullableIdempotencyKeyFailureResponse {
	return &NullableIdempotencyKeyFailureResponse{value: val, isSet: true}
}

func (v NullableIdempotencyKeyFailureResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdempotencyKeyFailureResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


