/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.4.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContactPropertyCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactPropertyCreateRequest{}

// ContactPropertyCreateRequest struct for ContactPropertyCreateRequest
type ContactPropertyCreateRequest struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type _ContactPropertyCreateRequest ContactPropertyCreateRequest

// NewContactPropertyCreateRequest instantiates a new ContactPropertyCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactPropertyCreateRequest(name string, type_ string) *ContactPropertyCreateRequest {
	this := ContactPropertyCreateRequest{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewContactPropertyCreateRequestWithDefaults instantiates a new ContactPropertyCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactPropertyCreateRequestWithDefaults() *ContactPropertyCreateRequest {
	this := ContactPropertyCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ContactPropertyCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContactPropertyCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContactPropertyCreateRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ContactPropertyCreateRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContactPropertyCreateRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContactPropertyCreateRequest) SetType(v string) {
	o.Type = v
}

func (o ContactPropertyCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactPropertyCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ContactPropertyCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContactPropertyCreateRequest := _ContactPropertyCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContactPropertyCreateRequest)

	if err != nil {
		return err
	}

	*o = ContactPropertyCreateRequest(varContactPropertyCreateRequest)

	return err
}

type NullableContactPropertyCreateRequest struct {
	value *ContactPropertyCreateRequest
	isSet bool
}

func (v NullableContactPropertyCreateRequest) Get() *ContactPropertyCreateRequest {
	return v.value
}

func (v *NullableContactPropertyCreateRequest) Set(val *ContactPropertyCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContactPropertyCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContactPropertyCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactPropertyCreateRequest(val *ContactPropertyCreateRequest) *NullableContactPropertyCreateRequest {
	return &NullableContactPropertyCreateRequest{value: val, isSet: true}
}

func (v NullableContactPropertyCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactPropertyCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


